# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Neighborhood', '0002_auto_20180527_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Neighborhood.UserProfile'),
        ),
    ]
