# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Neighborhood', '0003_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Neighborhood.Neighborhood'),
        ),
    ]
