# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Neighborhood', '0004_auto_20180527_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Neighborhood.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='healthcare_centre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='healthcare_no',
            field=models.IntegerField(blank=True, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='police_location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='police_no',
            field=models.IntegerField(blank=True, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='police_station',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Neighborhood.Neighborhood'),
        ),
    ]
