# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Neighborhood', '0006_auto_20180529_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Neighborhood.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Neighborhood.Neighborhood'),
        ),
    ]
