# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neighborhood', '0008_auto_20180529_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identification',
            field=models.IntegerField(null=True),
        ),
    ]
